<template>
  <div>
    <img v-bind:src="options.img" @click="editCropper()" title="Click Upload profile picture" class="img-circle img-lg" />
    <el-dialog :title="title" :visible.sync="open" width="800px" append-to-body @opened="modalOpened">
      <el-row>
        <el-col :xs="24" :md="12" :style="{height: '350px'}">
          <vue-cropper
            ref="cropper"
            :img="options.img"
            :info="true"
            :autoCrop="options.autoCrop"
            :autoCropWidth="options.autoCropWidth"
            :autoCropHeight="options.autoCropHeight"
            :fixedBox="options.fixedBox"
            @realTime="realTime"
            v-if="visible"
          />
        </el-col>
        <el-col :xs="24" :md="12" :style="{height: '350px'}">
          <div class="avatar-upload-preview">
            <img :src="previews.url" :style="previews.img" />
          </div>
        </el-col>
      </el-row>
      <br />
      <el-row>
        <el-col :lg="2" :md="2">
          <el-upload action="#" :http-request="requestUpload" :show-file-list="false" :before-upload="beforeUpload">
            <el-button size="small">
              upload
              <i class="el-icon-upload el-icon--right"></i>
            </el-button>
          </el-upload>
        </el-col>
        <el-col :lg="{span: 1, offset: 2}" :md="2">
          <el-button icon="el-icon-plus" size="small" @click="changeScale(1)"></el-button>
        </el-col>
        <el-col :lg="{span: 1, offset: 1}" :md="2">
          <el-button icon="el-icon-minus" size="small" @click="changeScale(-1)"></el-button>
        </el-col>
        <el-col :lg="{span: 1, offset: 1}" :md="2">
          <el-button icon="el-icon-refresh-left" size="small" @click="rotateLeft()"></el-button>
        </el-col>
        <el-col :lg="{span: 1, offset: 1}" :md="2">
          <el-button icon="el-icon-refresh-right" size="small" @click="rotateRight()"></el-button>
        </el-col>
        <el-col :lg="{span: 2, offset: 6}" :md="2">
          <el-button type="primary" size="small" @click="uploadImg()">mention Hand in</el-button>
        </el-col>
      </el-row>
    </el-dialog>
  </div>
</template>

<script>
import store from "@/store";
import { VueCropper } from "vue-cropper";
import { uploadAvatar } from "@/api/system/user";

export default {
  components: { VueCropper },
  props: {
    user: {
      type: Object
    }
  },
  data() {
    return {
      // Whether to display the pop-up layer
      open: false,
      // Whether or not showncropper
      visible: false,
      // Pop-up layer title
      title: "Modify the picture",
      options: {
        img: store.getters.avatar, //Crop the address of the picture
        autoCrop: true, // Whether a screenshot box is generated by default
        autoCropWidth: 200, // The default screenshot box width is generated
        autoCropHeight: 200, // The height of the screenshot box is generated by default
        fixedBox: true // Fixed the screenshot size No change allowed
      },
      previews: {}
    };
  },
  methods: {
    // Edit avatar
    editCropper() {
      this.open = true;
    },
    // Open the callback at the end of the pop-up layer
    modalOpened() {
      this.visible = true;
    },
    // Override the default upload behavior
    requestUpload() {
    },
    // Rotate to the left
    rotateLeft() {
      this.$refs.cropper.rotateLeft();
    },
    // Spin to the right
    rotateRight() {
      this.$refs.cropper.rotateRight();
    },
    // zooming
    changeScale(num) {
      num = num || 1;
      this.$refs.cropper.changeScale(num);
    },
    // Upload preprocessing
    beforeUpload(file) {
      if (file.type.indexOf("image/") == -1) {
        this.msgError("File format error,Please upload the image type,Such as:JPG,PNGFile with suffix。");
      } else {
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => {
          this.options.img = reader.result;
        };
      }
    },
    // To upload pictures
    uploadImg() {
      this.$refs.cropper.getCropBlob(data => {
        let formData = new FormData();
        formData.append("avatarfile", data);
        uploadAvatar(formData).then(response => {
          if (response.code === 200) {
            this.open = false;
            this.options.img = process.env.VUE_APP_BASE_API + response.imgUrl;
            store.commit('SET_AVATAR', this.options.img);
            this.msgSuccess("Modify the success");
          }
          this.visible = false;
        });
      });
    },
    // Real-time preview
    realTime(data) {
      this.previews = data;
    }
  }
};
</script>